### ISSUE TITLE
Compile error in pauline2raw.cpp

### ISSUE THREAD

**Issue by kitahei88** [yas-sim/fdc_bitstream#24]
Hello.
Thank you for your repository.

I have compiled under Linux(Gentoo, gcc 13.2.1, cmake 3.28.5 ) and cmake says some errors.
 
> fdc_bitstream/include/bit_array.h:11:17: error : uint8_t’ was not declared in this scope

I added ' #include <stdint.h>' in bit_array.h

> fdc_bitstream/fdc_bitstream/vfo_pid3.cpp:112:12: error: ‘fabs’ was not declared in this scope; did you mean ‘labs’?
  112 |         if(fabs(m_current_gain-m_gain_used)<gain_change_speed)

I added ' #include <math.h>' in fdc_vfo_base.h

> 'cannot bind non-const lvalue reference of type ‘std::_Bit_reference&’ to an rvalue of type ‘std::_Bit_iterator::reference’
  260 |         for(auto &b : indexHole)'

I cannot repair it.
It will compile under VisualStudio but GCC will complain.

Please help.

**Comment by yas-sim** [comment]
I tried to build the project on the WSL2 Ubuntu 20.04 environment. I know this environment is not up to date, but this is my only active Linux environment. 
I encountered some errors, so I added some included files and modified the code, and the errors disappeared.
Could you try again?

**Comment by kitahei88** [comment]
Thank you.　
Two changes were still needed ( ' #include <stdint.h>' in bit_array.h and ' #include <math.h>' in fdc_vfo_base.h).
But I can build to the end and work OK.
